# Generated by Django 5.2 on 2025-05-04 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_incident_category_incident_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
