# Generated by Django 5.2 on 2025-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_text_comment_content_report_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('unauthorized access', 'Unauthorized Access'), ('data leak', 'Data Leak'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
